name: runner_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  supabase_flutter: ^2.8.1 # supabase에서 supabase_flutter: ^2.8.1로 변경
  google_maps_flutter: ^2.15.0
  geolocator: ^14.0.2
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  flutter_foreground_task: ^6.1.1
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/badges/generated/runner_badges_board.png
    - assets/badges/generated/icons/
    - assets/badges/generated/tiles/
