CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";

CREATE TABLE IF NOT EXISTS "public"."run_segment_ai_features" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE,
    "run_id" bigint NOT NULL REFERENCES "public"."runs"("id") ON DELETE CASCADE,
    "split_index" integer NOT NULL,
    "embedding" extensions.vector(384),
    "feature_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "summary_text" text NOT NULL,
    "split_pace_s_per_km" double precision,
    "avg_pace_until_split_s_per_km" double precision,
    "pace_delta_prev_s" double precision,
    "pace_delta_avg_s" double precision,
    "distance_m" double precision,
    "duration_s" double precision,
    "ascent_m" double precision,
    "next_split_pace_s_per_km" double precision,
    "next_pace_delta_s" double precision,
    "next_outcome" text,
    "embedding_model" text DEFAULT 'gte-small'::text NOT NULL,
    "embedding_status" text DEFAULT 'pending'::text NOT NULL,
    "error_message" text,
    "embedded_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "run_segment_ai_features_status_chk" CHECK (
        "embedding_status" = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text])
    ),
    CONSTRAINT "run_segment_ai_features_split_index_chk" CHECK ("split_index" > 0),
    CONSTRAINT "run_segment_ai_features_run_split_uniq" UNIQUE ("run_id", "split_index")
);

ALTER TABLE "public"."run_segment_ai_features" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "idx_run_segment_ai_features_user_split"
    ON "public"."run_segment_ai_features" USING btree ("user_id", "split_index");

CREATE INDEX IF NOT EXISTS "idx_run_segment_ai_features_user_created"
    ON "public"."run_segment_ai_features" USING btree ("user_id", "created_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_run_segment_ai_features_status"
    ON "public"."run_segment_ai_features" USING btree ("embedding_status", "created_at");

CREATE INDEX IF NOT EXISTS "idx_run_segment_ai_features_embedding_ivfflat"
    ON "public"."run_segment_ai_features" USING ivfflat ("embedding" extensions.vector_cosine_ops)
    WITH (lists = 100)
    WHERE "embedding" IS NOT NULL;

CREATE OR REPLACE TRIGGER "trg_run_segment_ai_features_updated_at"
    BEFORE UPDATE ON "public"."run_segment_ai_features"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_run_ai_updated_at"();

ALTER TABLE "public"."run_segment_ai_features" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "run_segment_ai_features_select_own"
    ON "public"."run_segment_ai_features"
    FOR SELECT
    TO authenticated
    USING ("user_id" = auth.uid());

CREATE OR REPLACE FUNCTION "public"."match_similar_run_segments"(
    "p_user_id" uuid,
    "p_split_index" integer,
    "p_embedding" extensions.vector(384),
    "p_feature_json" jsonb DEFAULT '{}'::jsonb,
    "p_exclude_run_id" bigint DEFAULT NULL,
    "p_limit" integer DEFAULT 5
) RETURNS TABLE (
    "run_id" bigint,
    "split_index" integer,
    "summary_text" text,
    "feature_json" jsonb,
    "split_pace_s_per_km" double precision,
    "avg_pace_until_split_s_per_km" double precision,
    "pace_delta_prev_s" double precision,
    "pace_delta_avg_s" double precision,
    "ascent_m" double precision,
    "next_split_pace_s_per_km" double precision,
    "next_pace_delta_s" double precision,
    "next_outcome" text,
    "similarity_score" double precision,
    "embedding_score" double precision,
    "split_index_score" double precision,
    "numeric_score" double precision
)
    LANGUAGE sql
    STABLE
    AS $$
WITH candidate_scores AS (
  SELECT
    f.run_id,
    f.split_index,
    f.summary_text,
    f.feature_json,
    f.split_pace_s_per_km,
    f.avg_pace_until_split_s_per_km,
    f.pace_delta_prev_s,
    f.pace_delta_avg_s,
    f.ascent_m,
    f.next_split_pace_s_per_km,
    f.next_pace_delta_s,
    f.next_outcome,
    CASE
      WHEN p_embedding IS NULL OR f.embedding IS NULL THEN 0::double precision
      ELSE greatest(0::double precision, 1::double precision - (f.embedding OPERATOR(extensions.<=>) p_embedding))
    END AS embedding_score,
    exp(-(abs(f.split_index - p_split_index)::double precision / 1.5))::double precision AS split_index_score,
    exp(-least(60::double precision, (
      (
        coalesce(abs(f.split_pace_s_per_km - (p_feature_json->>'split_pace_s_per_km')::double precision) / 90.0, 0) +
        coalesce(abs(f.avg_pace_until_split_s_per_km - (p_feature_json->>'avg_pace_until_split_s_per_km')::double precision) / 90.0, 0) +
        coalesce(abs(f.pace_delta_prev_s - (p_feature_json->>'pace_delta_prev_s')::double precision) / 60.0, 0) +
        coalesce(abs(f.pace_delta_avg_s - (p_feature_json->>'pace_delta_avg_s')::double precision) / 60.0, 0) +
        coalesce(abs(f.ascent_m - (p_feature_json->>'ascent_m')::double precision) / 30.0, 0)
      ) / 5.0
    )))::double precision AS numeric_score,
    row_number() OVER (
      PARTITION BY f.run_id
      ORDER BY
        CASE
          WHEN p_embedding IS NULL OR f.embedding IS NULL THEN 0::double precision
          ELSE greatest(0::double precision, 1::double precision - (f.embedding OPERATOR(extensions.<=>) p_embedding))
        END DESC,
        abs(f.split_index - p_split_index) ASC,
        f.created_at DESC
    ) AS run_rank
  FROM public.run_segment_ai_features f
  WHERE f.user_id = p_user_id
    AND f.embedding_status = 'completed'
    AND f.embedding IS NOT NULL
    AND (p_exclude_run_id IS NULL OR f.run_id <> p_exclude_run_id)
    AND f.split_index BETWEEN greatest(1, p_split_index - 1) AND p_split_index + 1
),
limited_candidates AS (
  SELECT *
  FROM candidate_scores
  WHERE run_rank <= 2
)
SELECT
  run_id,
  split_index,
  summary_text,
  feature_json,
  split_pace_s_per_km,
  avg_pace_until_split_s_per_km,
  pace_delta_prev_s,
  pace_delta_avg_s,
  ascent_m,
  next_split_pace_s_per_km,
  next_pace_delta_s,
  next_outcome,
  ((embedding_score * 0.60) + (split_index_score * 0.20) + (numeric_score * 0.20))::double precision AS similarity_score,
  embedding_score,
  split_index_score,
  numeric_score
FROM limited_candidates
ORDER BY similarity_score DESC
LIMIT greatest(1, least(coalesce(p_limit, 5), 10));
$$;

ALTER FUNCTION "public"."match_similar_run_segments"(uuid, integer, extensions.vector(384), jsonb, bigint, integer) OWNER TO "postgres";

GRANT SELECT ON TABLE "public"."run_segment_ai_features" TO "authenticated";
GRANT ALL ON TABLE "public"."run_segment_ai_features" TO "service_role";
GRANT USAGE, SELECT ON SEQUENCE "public"."run_segment_ai_features_id_seq" TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."match_similar_run_segments"(uuid, integer, extensions.vector(384), jsonb, bigint, integer) TO "service_role";
